export const mockRoasts = [
  {
    roast: `Oh look, another person who thinks they're ready for this level of digital destruction. Let me paint you a picture of what I see here.\n\nYou're probably the type of person who introduces themselves at parties with their full LinkedIn bio, aren't you? I bet you have strong opinions about coffee that nobody asked for.\n\nYour hobbies list reads like a desperate attempt to seem interesting on dating apps. "I enjoy hiking" - yeah right, walking to the fridge doesn't count as a nature adventure.\n\nThe fact that you willingly signed up to get roasted by an AI tells me everything I need to know about your decision-making skills. It's like volunteering to be a crash test dummy, except less useful to society.\n\nBut hey, at least you're self-aware enough to know you need some digital humbling. That's... something, I guess.\n\nNow go touch some grass and reconsider your life choices! 🔥`,
    intensity: "medium"
  },
  {
    roast: `Buckle up buttercup, because I'm about to serve you a reality check with a side of emotional damage.\n\nFirst off, your age tells me you've had plenty of time to figure things out, and yet here you are, asking a robot to hurt your feelings. That's what we call "character development" in reverse.\n\nYour occupation probably involves explaining to people why you're "passionate about synergy" while secretly googling "how to adult" during lunch breaks.\n\nAnd don't get me started on your hobbies - they sound like you picked them from a "How to Be Interesting for Dummies" book. I bet you tell people you're a "foodie" because you tried a new Starbucks drink once.\n\nThe most embarrassing thing about you isn't what you wrote down - it's that you thought this was a good idea. But I admire the confidence! It takes real courage to walk into digital battle so unprepared.\n\nNow excuse me while I go compute something more challenging, like why people put pineapple on pizza. 🍕💀`,
    intensity: "savage"
  },
  {
    roast: `Well well well, what do we have here? Another brave soul ready for some gentle AI roasting.\n\nLet me guess - you're the type of person who reads the terms and conditions, aren't you? Your attention to detail in this form is both admirable and slightly concerning.\n\nYour personality traits suggest you're probably really fun at parties... if "fun" means explaining the optimal way to organize a spice rack for 20 minutes.\n\nI notice you picked a light roast level, which honestly matches your probably-too-cautious approach to life. You're the person who tests the water temperature with their toe for 10 minutes before getting in the pool.\n\nBut you know what? There's something endearing about someone who's brave enough to try this while also playing it safe. It's like ordering the spiciest thing on the menu and then asking for extra milk.\n\nKeep being wonderfully, predictably you! The world needs more people who read instruction manuals. 🌱✨`,
    intensity: "light"
  },
  {
    roast: `*cracks digital knuckles* Oh, you really asked for the savage treatment? Your funeral, my friend.\n\nLet me break this down for you in terms your probably-limited attention span can handle: You're what happens when someone's personality gets assembled by IKEA - missing a few essential pieces and the instructions are in Swedish.\n\nYour hobbies read like a Pinterest board titled "Things I'll Try Next Monday" that hasn't been updated since 2019. I bet your idea of "living dangerously" is mixing two different Netflix genres in your watch list.\n\nThe embarrassing fact you shared? That's not even your most embarrassing moment - filling out this form and clicking "savage mode" definitely takes the crown.\n\nYou're like a participation trophy that gained consciousness and decided to enter a roasting competition. Bold strategy, questionable execution, zero chance of survival.\n\nBut hey, at least you're consistent - consistently making choices that would make a Magic 8-Ball question its own judgment.\n\nGo sit in the corner and think about what you've done. The internet will remember this. 💀🔥⚡`,
    intensity: "savage"
  },
  {
    roast: `Oh dear, another victim has wandered into my digital colosseum! Let me adjust my roasting settings to "medium rare" for you.\n\nYour form answers suggest you're the type of person who has strong opinions about Marvel movies and isn't afraid to share them at inappropriate times. Probably owns way too many novelty t-shirts too.\n\nI love how you described your personality - it's like reading a resume where someone tried to make "I binge-watch Netflix" sound like a marketable skill. "Highly proficient in fictional character analysis with a specialization in determining plot holes."\n\nYour occupation tells me you're either really good at pretending to understand spreadsheets, or you've mastered the art of looking busy while actually planning your lunch.\n\nThe fact that you chose medium roast shows you have just enough self-awareness to know you can't handle the full savage experience, but enough confidence to avoid the kiddie pool. Respect!\n\nNow go forth and continue being moderately entertaining at social gatherings! 🎯🔥`,
    intensity: "medium"
  }
];